# Generated by Django 5.0.4 on 2024-04-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HashtagMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('mentions', models.IntegerField()),
                ('upvotes', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('first_post_time_hours_ago', models.IntegerField()),
            ],
        ),
    ]
