# Generated by Django 5.0.4 on 2024-05-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagsapp', '0003_hashtagmetrics_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtagmetrics',
            name='network',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
