# Generated by Django 5.0.4 on 2024-05-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagsapp', '0004_hashtagmetrics_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashtagMetricsX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('mentions', models.IntegerField()),
                ('retweets', models.IntegerField()),
                ('quotes', models.IntegerField()),
                ('views', models.IntegerField()),
                ('first_post_time_hours_ago', models.IntegerField()),
                ('relative_attraction', models.FloatField()),
                ('topic', models.CharField(max_length=255)),
                ('network', models.CharField(max_length=255)),
            ],
        ),
    ]
